export const actionTypes = {
  UPDATE_USER_POINTS: 'UPDATE_USER_POINTS',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
  UPDATE_FILTER: 'UPDATE_FILTER',
  PREVIOUS_PAGE: 'PREVIOUS_PAGE',
  NEXT_PAGE: 'NEXT_PAGE',
  UPDATE_SELECTED: 'UPDATE_SELECTED',
  UPDATE_MODAL: 'UPDATE_MODAL',
  UPDATE_LOADING: 'UPDATE_LOADING',
  UPDATE_HISTORY: 'UPDATE_HISTORY',
  UPDATE_LOADING_HISTORY: 'UPDATE_LOADING_HISTORY',
  PREVIOUS_HISTORY_ITEM: 'PREVIOUS_HISTORY_ITEM',
  NEXT_HISTORY_ITEM: 'NEXT_HISTORY_ITEM',
  UPDATE_SELECTED_VALUE: 'UPDATE_SELECTED_VALUE',
  TOGGLE_MESSAGE: 'TOGGLE_MESSAGE'
}

export default actionTypes
